// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5yVULWWsIK9Rlk0KF_e94g4iGliN4t3g',
    appId: '1:8071228171:android:d034050662277c0be7100e',
    messagingSenderId: '8071228171',
    projectId: 'example-6fd34',
    storageBucket: 'example-6fd34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCItwZNOdOB95uJLrvJKj4ygZXQqlksBTk',
    appId: '1:8071228171:ios:064d45663c3bee09e7100e',
    messagingSenderId: '8071228171',
    projectId: 'example-6fd34',
    storageBucket: 'example-6fd34.appspot.com',
    iosClientId: '8071228171-m3c3eocbtd8jm4cqll2tg1pv7rb49ji8.apps.googleusercontent.com',
    iosBundleId: 'com.calvinproject.app',
  );
}
